/*
 * All artwork in the app is defined here as flat polygon geometry on a
 * 100 x 100 grid. Nothing is imported, traced or generated by a tool: the same
 * point lists drive the inline SVG in the UI and the PNG launcher icons
 * rasterised by tools/gen-icons.mjs.
 *
 * Every shape is straight-edged: no curves, no rounded joins, no gradients.
 */

/**
 * The bull head. Sub-polygons never overlap, so an even-odd fill renders the
 * eyes and nostrils as knockouts and the horns/ears as solid extensions.
 */
export const BULL = [
  // Skull: flat brow, tapering to a blunt muzzle.
  [[30, 30], [70, 30], [76, 52], [66, 74], [34, 74], [24, 52]],
  // Left horn, hinged on the skull edge between (30,30) and (27,40).
  [[30, 30], [16, 22], [2, 4], [9, 17], [21, 31], [27, 40]],
  // Right horn.
  [[70, 30], [84, 22], [98, 4], [91, 17], [79, 31], [73, 40]],
  // Ears, pinned lower on the skull so they read apart from the horns.
  [[26, 44], [6, 49], [24, 53]],
  [[74, 44], [94, 49], [76, 53]],
  // Eyes (knockout).
  [[37, 44], [45, 44], [45, 52], [37, 52]],
  [[55, 44], [63, 44], [63, 52], [55, 52]],
  // Nostrils (knockout).
  [[43, 60], [48, 60], [48, 65], [43, 65]],
  [[52, 60], [57, 60], [57, 65], [52, 65]],
];

/** Four stacked bars: the app mark, echoing the four rows of the board. */
export const MARK = [
  [[10, 16], [90, 16], [90, 28], [10, 28]],
  [[10, 34], [74, 34], [74, 46], [10, 46]],
  [[10, 52], [58, 52], [58, 64], [10, 64]],
  [[10, 70], [42, 70], [42, 82], [10, 82]],
];

function pathData(polygons) {
  return polygons
    .map((poly) => 'M' + poly.map((p) => p[0] + ' ' + p[1]).join('L') + 'Z')
    .join('');
}

export const BULL_PATH = pathData(BULL);
export const MARK_PATH = pathData(MARK);

/**
 * Inline SVG for the bull head.
 * @param {{size?: number|string, cls?: string, title?: string}} opts
 */
export function bullSvg(opts = {}) {
  const size = opts.size == null ? '1em' : opts.size;
  const cls = opts.cls ? ` class="${opts.cls}"` : '';
  return (
    `<svg${cls} width="${size}" height="${size}" viewBox="0 0 100 100" ` +
    'aria-hidden="true" focusable="false">' +
    `<path d="${BULL_PATH}" fill="currentColor" fill-rule="evenodd"/></svg>`
  );
}

export function markSvg(opts = {}) {
  const size = opts.size == null ? '1em' : opts.size;
  const cls = opts.cls ? ` class="${opts.cls}"` : '';
  return (
    `<svg${cls} width="${size}" height="${size}" viewBox="0 0 100 100" ` +
    'aria-hidden="true" focusable="false">' +
    `<path d="${MARK_PATH}" fill="currentColor"/></svg>`
  );
}

/* ------------------------------------------------------------------ *
 * Interface glyphs. Same discipline: straight strokes, square caps.
 * ------------------------------------------------------------------ */

const GLYPHS = {
  plus: 'M46 20H54V46H80V54H54V80H46V54H20V46H46Z',
  enter: 'M20 46H62L46 30L52 24L78 50L52 76L46 70L62 54H20Z',
  back: 'M80 46H38L54 30L48 24L22 50L48 76L54 70L38 54H80Z',
  close: 'M26 20L50 44L74 20L80 26L56 50L80 74L74 80L50 56L26 80L20 74L44 50L20 26Z',
  check: 'M40 62L74 28L80 34L40 74L20 54L26 48Z',
  copy: 'M28 16H72V26H38V72H28ZM44 32H84V88H44ZM52 40V80H76V40Z',
  sun: 'M46 6H54V22H46ZM46 78H54V94H46ZM6 46H22V54H6ZM78 46H94V54H78ZM17 23L23 17L34 28L28 34ZM83 23L77 17L66 28L72 34ZM17 77L23 83L34 72L28 66ZM83 77L77 83L66 72L72 66ZM42 30H58L70 42V58L58 70H42L30 58V42Z',
  moon: 'M50 12L23 23L12 50L23 77L50 88L68 74L74 50L68 26Z',
  standings: 'M10 20H28V34H10ZM36 20H90V34H36ZM10 43H28V57H10ZM36 43H78V57H36ZM10 66H28V80H10ZM36 66H64V80H36Z',
  signal: 'M12 66H26V84H12ZM32 52H46V84H32ZM52 38H66V84H52ZM72 24H86V84H72Z',
  warn: 'M50 12L92 84H8ZM46 40H54V62H46ZM46 68H54V78H46Z',
};

/**
 * Inline SVG for a named interface glyph.
 * @param {keyof GLYPHS} name
 */
export function icon(name, opts = {}) {
  const d = GLYPHS[name];
  if (!d) throw new Error('unknown glyph: ' + name);
  const size = opts.size == null ? '1em' : opts.size;
  const cls = opts.cls ? ` class="${opts.cls}"` : '';
  return (
    `<svg${cls} width="${size}" height="${size}" viewBox="0 0 100 100" ` +
    'aria-hidden="true" focusable="false">' +
    `<path d="${d}" fill="currentColor" fill-rule="evenodd"/></svg>`
  );
}
